// src/lib/components/home/About.svelte
<div class="about-content">
	<h2>Something about me</h2>
	Hey, I’m Paweł (aka RaiderHCPlay) => a student & web dev coding in Neovim. I love experimenting with
	new tech like Ruby or Rust. When I’m not coding, you'll find me watching anime, reading manga, or playing
	a peak game like Persona 3 Reload. Currently, I focus on understanding others' code to learn, and building
	projects to sharpen my skills. Also, I enjoy Svelte btw.
</div>

// src/components/home/About.tsx
export default function AboutSection() {
  return (
    <div className="about-content">
      <h2>Something about me</h2>
      Hey, I’m Paweł (aka RaiderHCPlay) — a student & self-taught dev coding in
      Neovim, building UIs with TypeScript, React & Sass, and experimenting with
      Tailwind, Rust, and Ruby. When I’m not coding, I’m watching anime, reading
      manga (JoJo is peak), or destroying shadows in Persona 3 — all while vibing to
      peak soundtracks. Currently cooking something cool. Stay tuned.
    </div>
  );
}
