// src/components/home/About.svelte
<div class="about-content">
	<h2>Something about me</h2>
	Hey, I’m Paweł (aka RaiderHCPlay) — a student and self-taught web dev coding in Neovim. I'm experimenting
	with Ruby for scripting, Svelte for UIs and Prisma as an ORM. When I’m not coding, you'll find me watching
	anime, reading manga, or playing a peak game like Persona 3 Reload — all while vibing to peak soundtracks.
	Currently cooking up something cool. Stay tuned.
</div>

// src/components/home/About.tsx
export default function AboutSection() {
  return (
    <div className="about-content">
      <h2>Something about me</h2>
      Hey, I’m Paweł (aka RaiderHCPlay) — a student & self-taught dev coding in
      Neovim, building UIs with TypeScript, React & Sass, and experimenting with
      Tailwind and Ruby. When I’m not coding, I’m watching anime, reading manga
      (JoJo is peak), or destroying shadows in Persona 3 — all while vibing to
      peak soundtracks. Currently cooking something cool. Stay tuned.
    </div>
  );
}
